schema:
  - http://localhost:5000/graphql:
      headers:
        Authorization: ${GRAPHQL_AUTH_TOKEN}
documents:
  - './hugmenow/web/src/graphql/**/*.js'
  - './hugmenow/web/src/**/*.jsx'
extensions:
  codegen:
    generates:
      ./hugmenow/web/src/generated/graphql.tsx:
        plugins:
          - typescript
          - typescript-operations
          - typescript-react-apollo
        config:
          withHooks: true
          withComponent: false
          withHOC: false
          skipTypename: false
          avoidOptionals: true
      ./hugmenow/web/src/generated/schema.graphql:
        plugins:
          - schema-ast
  inspector:
    diff:
      baseSchema: ./hugmenow/api/src/schema.gql
      changedSchema: ./hugmenow/web/src/generated/schema.graphql
    validate:
      schema: ./hugmenow/web/src/generated/schema.graphql
      documents:
        - './hugmenow/web/src/graphql/**/*.js'
        - './hugmenow/web/src/**/*.jsx'
  mesh:
    artifactsDir: ./mesh-artifacts
    sources:
      - name: HugMeNowAPI
        handler:
          graphql:
            endpoint: http://localhost:5000/graphql
            operationHeaders:
              Authorization: ${GRAPHQL_AUTH_TOKEN}
    transforms:
      - namingConvention:
          typeNames: 'pascalCase'
          fieldNames: 'camelCase'
          enumValues: 'upperCase'
    plugins:
      - responseCache:
          ttl: 300 # 5 minutes
      - parserCache: {}
      - validationCache: {}
      - depthLimit:
          maxDepth: 10