// Simple Express server for testing
import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = 5000;

// Serve static files from the current directory
app.use(express.static(__dirname));

// Serve a simple HTML page
app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'test.html'));
});

// Dynamic test route
app.get('/dynamic', (req, res) => {
  res.send(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>HugMeNow Dynamic Test</title>
      <style>
        body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
        h1 { color: #5E35B1; }
      </style>
    </head>
    <body>
      <h1>HugMeNow Dynamic Test Page</h1>
      <p>This is a dynamic test page generated by the server.</p>
      <p>Current time: ${new Date().toLocaleString()}</p>
      <p><a href="/">Go back to home</a></p>
    </body>
    </html>
  `);
});

// Echo request info for diagnostics
app.get('/echo', (req, res) => {
  const requestInfo = {
    headers: req.headers,
    url: req.url,
    method: req.method,
    remoteAddress: req.connection.remoteAddress,
    timestamp: new Date().toISOString()
  };
  
  console.log('Request info:', requestInfo);
  
  res.json(requestInfo);
});

// Logging middleware
app.use((req, res, next) => {
  console.log(`[${new Date().toISOString()}] ${req.method} ${req.url}`);
  next();
});

// Start the server
app.listen(PORT, '0.0.0.0', () => {
  console.log(`Simple test server running on http://0.0.0.0:${PORT}`);
  console.log(`Access static test page at: http://0.0.0.0:${PORT}/test.html`);
  console.log(`Access dynamic test page at: http://0.0.0.0:${PORT}/dynamic`);
});